sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t stizianel/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true stizianel/docker-react npm run test 